version: '3.2'

volumes:
  mysql:
    driver: 'local'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html:cached

  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./docker/sql:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_TEST_DATABASE=${DATABASE_TEST_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --sql_mode=""

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
       - "8081:80"
    volumes:
       - /sessions
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=${DATABASE_USERNAME}
      - PMA_PASSWORD=${DATABASE_PASSWORD}
    links:
      - mysql
